stages:

- stage: preprod_blue
  displayName: preprod_blue

  dependsOn: STAGE
  condition: succeeded()


  jobs:

  - template: ../jobs/deploy-job.yml
    parameters:
      environmentName: preprod_blue