trigger: none

pr: none

stages:

- template: ../stages/build-stage.yml

- template: ../stages/dev-stage.yml

- template: ../stages/qa-stage.yml

- template: ../stages/uat-stage.yml

- template: ../stages/approval-stage.yml

- template: ../stages/stage-stage.yml

- template: ../stages/preprod-stage.yml

- template: ../stages/prod-stage.yml

- template: ../stages/dr-stage.yml